### ISSUE TITLE
Only one warning on closing modified file

### ISSUE THREAD

**Issue by Esgorhannoth** [mtimkovich/em#3]
Is it by design that ```isModified``` sets ```e.modified``` to ```false``` after first warning?
```go
func (e *Editor) isModified() bool {
    if e.modified {
        e.Error("warning: file modified")
        e.modified = false
        return true
    } else {
        return false
    }
}
```

And I guess it should be ```"warning: buffer modified"``` because file is not modified yet.

**Comment by mtimkovich** [comment]
Yeah, it is. It mimics the same behavior as ed in that situation

**Comment by Esgorhannoth** [comment]
Don't know about that. My ed refuses to open new file with ```e``` command until I save the buffer. Only with ```E``` it opens another file over modified one without questions :)

**Comment by mtimkovich** [comment]
Oh interesting. In that case, the version of ed on my computer (OSX) uses the behavior I described above.
