### ISSUE TITLE
Commands fail when no file is open

### ISSUE THREAD

**Issue by Esgorhannoth** [mtimkovich/em#4]
When starting ./em with no argument I get some strange errors:
```
i
?
h
?
q
?
```

The only way to execute a command on an empty file is to prefix it with ```1,0```
```
1,0q
bash> _
```

My guess is that ```NewEditor()``` should initialize ```e.line``` to ```1```.

**Comment by mtimkovich** [comment]
Thanks, @Esgorhannoth!

45b22736784077f4b5e3a9c2b37e4c9c1a7c3258
