### ISSUE TITLE
'Enter' to go to next line

### ISSUE THREAD

**Issue by Esgorhannoth** [mtimkovich/em#5]
Original ```ed``` has this useful feature. You just hit ```Enter``` and it is assumed that you want ```+1,+1p```.

Replacing this snipper in ```Parse```:
```go
    if len(text) == 0 {
        e.Error("invalid address")
        return 0, 0, ""
    }
```
with this:
```go
    if len(text) == 0 {
	  if (e.line + 1 >= e.buffer.Len()) {
              e.Error("invalid address")
              return 0, 0, ""
	  } else {
              return e.line+1, e.line+1, "p"
	  }
    }

```
creates just that effect.

**Comment by mtimkovich** [comment]
Excellent suggestion! I added it in 6e05a4eadb074c21129fa670b6cf9f165a3671fb.
